### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by trivialkettle**
I am not sure if you want to provide the program as docker image, but since I want to use it in docker, I provide my Dockerfile here and added a small section to README.md

### CODE REVIEW

**Comment by oscarotero** [comment]
Hi. Thanks but I prefer to don't include it. It requires to update it every time a new version is released, and the library can also be consumed in Deno (in fact, Deno is the primary language, Node is just an export format).

**Comment by trivialkettle** [comment]
We could also remove the version number. I guess if the github action push a new version, the `npm install` command will always install the current version. 

I can also switch from npm to the deno install flow.

**Comment by oscarotero** [comment]
Thanks but i'm not a docker expert and would prefer not including something I cannot maintain or improve. What I can do is to include a description with a link to your docker repo in the readme.md. What do you think?

**Comment by trivialkettle** [comment]
I don't have a dockerhub account and no experience with github actions to automatically create images for new releases. -> just leave it as it is. Thanks.

**Pull request closed without merging**
